In [ ]:
import pandas as pd

df = pd.read_csv('/content/Zomato-data-.csv')
display(df.head())

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

### Data Cleaning and Error Identification

First, let's check for missing values in each column and the overall data types.

In [ ]:
# Check for missing values
print('Missing values per column:')
display(df.isnull().sum())

# Check for duplicate rows
print('\nNumber of duplicate rows:')
display(df.duplicated().sum())

# Display data types
print('\nData types of each column:')
display(df.info())

Missing values per column:

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

Number of duplicate rows:

np.int64(0)

Data types of each column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

None

### Cleaning the `rate` column

The `rate` column is currently stored as an object, but it contains numerical ratings. We need to convert it to a numeric type. We will extract the numerical part and handle non-numeric entries.

In [ ]:
import numpy as np

def clean_rate(rate):
    if isinstance(rate, str):
        if ' ' in rate:
            # Handle cases like '4.1 /5'
            rate = rate.split(' ')[0]
        if '/' in rate:
            return float(rate.split('/')[0])
        elif rate == 'NEW' or rate == '-' or rate == 'nan':
            return np.nan
        else:
            try:
                return float(rate)
            except ValueError:
                return np.nan
    return rate


df['rate'] = df['rate'].apply(clean_rate)

print('Data types after cleaning the rate column:')
display(df.info())
print('\nMissing values in rate column after cleaning:')
display(df['rate'].isnull().sum())
print('\nFirst 5 rows of the cleaned rate column:')
display(df['rate'].head())

Data types after cleaning the rate column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    float64
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: float64(1), int64(2), object(4)
memory usage: 8.2+ KB

None

Missing values in rate column after cleaning:

np.int64(0)

First 5 rows of the cleaned rate column:

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64